/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import org.checkerframework.checker.units.qual.cd;

import engtelecom.poo.generic.*;

public class App {
    public static void main(String[] args) {
        Box<String> c = new Box<String>();
        String s = "Olá mundo";
        c.set(s);
        String s2 = c.getData();
    }
}